# Generated by Django 4.1 on 2022-10-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0047_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Order cancelled', 'Order cancelled'), ('Completed', 'Completed'), ('Out for Delivery', 'Out for Delivery'), ('Order confirmed', 'Order confirmed')], default='Order confirmed', max_length=150),
        ),
    ]
