# Generated by Django 4.1 on 2022-10-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0049_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Completed', 'Completed'), ('Order cancelled', 'Order cancelled'), ('Out for Delivery', 'Out for Delivery'), ('Shipped', 'Shipped'), ('Order confirmed', 'Order confirmed')], default='Order confirmed', max_length=150),
        ),
    ]
