# Generated by Django 4.1 on 2022-10-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_coupon_offer_value'),
        ('accountmanage', '0052_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='prod_disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Shipped', 'Shipped'), ('Order confirmed', 'Order confirmed'), ('Order cancelled', 'Order cancelled'), ('Returned', 'Returned'), ('Out for Delivery', 'Out for Delivery')], default='Order confirmed', max_length=150),
        ),
    ]
