# Generated by Django 4.1 on 2022-10-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0054_remove_orderitem_prod_disc_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Order cancelled', 'Order cancelled'), ('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed')], default='Order confirmed', max_length=150),
        ),
    ]
