# Generated by Django 4.1 on 2022-10-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0057_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='successordermod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Returned', 'Returned'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Order cancelled', 'Order cancelled')], default='Order confirmed', max_length=150),
        ),
    ]
