# Generated by Django 4.1 on 2022-10-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0059_alter_order_status_alter_successordermod_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed'), ('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Shipped', 'Shipped'), ('Order cancelled', 'Order cancelled')], default='Order confirmed', max_length=150),
        ),
        migrations.DeleteModel(
            name='successordermod',
        ),
    ]
