# Generated by Django 4.1 on 2022-10-22 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0060_alter_order_status_delete_successordermod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for Delivery', 'Out for Delivery'), ('Returned', 'Returned'), ('Order confirmed', 'Order confirmed'), ('Order cancelled', 'Order cancelled'), ('Completed', 'Completed'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=150),
        ),
        migrations.CreateModel(
            name='successordermod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountmanage.order')),
            ],
        ),
    ]
