# Generated by Django 4.1 on 2022-10-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0061_alter_order_status_successordermod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for Delivery', 'Out for Delivery'), ('Order cancelled', 'Order cancelled'), ('Order confirmed', 'Order confirmed'), ('Completed', 'Completed'), ('Shipped', 'Shipped'), ('Returned', 'Returned')], default='Order confirmed', max_length=150),
        ),
    ]
