# Generated by Django 4.1 on 2022-10-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0064_alter_order_status_alter_successordermod_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Order cancelled', 'Order cancelled'), ('Returned', 'Returned'), ('Order confirmed', 'Order confirmed'), ('Completed', 'Completed')], default='Order confirmed', max_length=150),
        ),
    ]
