# Generated by Django 4.0.6 on 2022-10-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0065_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Returned', 'Returned'), ('Out for Delivery', 'Out for Delivery'), ('Shipped', 'Shipped'), ('Order confirmed', 'Order confirmed'), ('Order cancelled', 'Order cancelled')], default='Order confirmed', max_length=150),
        ),
    ]
