# Generated by Django 4.1 on 2022-10-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0069_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for Delivery', 'Out for Delivery'), ('Order confirmed', 'Order confirmed'), ('Order cancelled', 'Order cancelled'), ('Completed', 'Completed'), ('Shipped', 'Shipped'), ('Returned', 'Returned')], default='Order confirmed', max_length=150),
        ),
    ]
