# Generated by Django 4.1 on 2022-10-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_categoryoffer_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_discount_price',
        ),
    ]
