# Generated by Django 4.1 on 2022-10-15 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_remove_product_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='offer_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
