# Generated by Django 4.1 on 2022-10-17 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_coupon_offer_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='offer_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)]),
        ),
    ]
