# Generated by Django 4.1 on 2022-10-21 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_alter_product_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_offer',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
