# Generated by Django 4.1 on 2022-10-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_alter_product_product_max_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_max_price',
            field=models.IntegerField(),
        ),
    ]
