# Generated by Django 4.1 on 2022-10-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
